ARG BASE_IMAGE=harbor-cn.lingmouai.com/asu/global-id-mapping:4.0
FROM ${BASE_IMAGE}

COPY --from=app processor.py cos_upload.py /app/docker/
COPY --from=app cos-sdk /app/.venv/lib/python3.11/site-packages/
